### ISSUE TITLE
2.11.11. Corte intermitente en la app cuando se intenta modificar.

### ISSUE THREAD

**Issue by tapiajimena** [fiubacampus2015/frontend#20]
Puede ser que se deba a que la app tarda en procesar la modificación y/o cargar el perfil por lo que al no tener la "rolita" de "cargando" se permite que el usuario continúe interactuando con la app. Yo empezaría agregando las rolitas.

**Comment by tapiajimena** [comment]
```
Process: com.fiuba.campus2015, PID: 8879
java.lang.IllegalStateException: Can't compress a recycled bitmap
        at android.graphics.Bitmap.checkRecycled(Bitmap.java:346)
        at android.graphics.Bitmap.compress(Bitmap.java:986)
        at com.fiuba.campus2015.fragments.PersonalDataFragment.getPhotoString(PersonalDataFragment.java:280)
```
